package br.com.agendamysql.view;

import br.com.agendamysql.controller.ContatoController;
import br.com.agendamysql.controller.TelefoneController;
import br.com.agendamysql.modelo.Contato;
import br.com.agendamysql.modelo.Telefone;
import br.com.agendamysql.tableModel.TableModelTelefone;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Agenda extends javax.swing.JFrame {

    private Contato contato;
    private ContatoController contatoController;
    private TelefoneController telefoneController;
    private Telefone telefone;
    private List<Telefone> telefones;
    private TableModelTelefone tmTelefone;

    public Agenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.contato = new Contato();
        this.contatoController = new ContatoController();
        this.telefoneController = new TelefoneController();
        this.telefone = new Telefone();
        this.telefones = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboOperadora = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTelefone = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        chRelatorio = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtCodigo.setEditable(false);
        txtCodigo.setMaximumSize(new java.awt.Dimension(60, 20));
        txtCodigo.setMinimumSize(new java.awt.Dimension(60, 20));
        txtCodigo.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(txtCodigo, gridBagConstraints);

        txtNome.setMaximumSize(new java.awt.Dimension(100, 20));
        txtNome.setMinimumSize(new java.awt.Dimension(100, 20));
        txtNome.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(txtNome, gridBagConstraints);

        jLabel1.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtEmpresa.setMaximumSize(new java.awt.Dimension(100, 20));
        txtEmpresa.setMinimumSize(new java.awt.Dimension(100, 20));
        txtEmpresa.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(txtEmpresa, gridBagConstraints);

        jLabel4.setText("Telefone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtTelefone.setMaximumSize(new java.awt.Dimension(100, 20));
        txtTelefone.setMinimumSize(new java.awt.Dimension(100, 20));
        txtTelefone.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(txtTelefone, gridBagConstraints);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setMaximumSize(new java.awt.Dimension(80, 20));
        btnAdicionar.setMinimumSize(new java.awt.Dimension(80, 20));
        btnAdicionar.setOpaque(false);
        btnAdicionar.setPreferredSize(new java.awt.Dimension(80, 20));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(btnAdicionar, gridBagConstraints);

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(80, 20));
        btnExcluir.setMinimumSize(new java.awt.Dimension(80, 20));
        btnExcluir.setOpaque(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(80, 20));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(btnExcluir, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agenda Telefone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Operadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(jLabel6, gridBagConstraints);

        cboOperadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Claro", "Tim", "Oi", "Nextel", "Vivo", "Fixo" }));
        cboOperadora.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 6);
        jPanel1.add(cboOperadora, gridBagConstraints);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(80, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(80, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(80, 100));

        tbTelefone.setAutoCreateRowSorter(true);
        tbTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTelefone.setMaximumSize(null);
        tbTelefone.setMinimumSize(null);
        tbTelefone.setOpaque(false);
        tbTelefone.setPreferredSize(null);
        jScrollPane2.setViewportView(tbTelefone);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 3, 6);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        btnNovo.setText("Novo");
        btnNovo.setOpaque(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(btnNovo, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendamysql/imagens/find.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(25, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 20));
        jButton1.setOpaque(false);
        jButton1.setPreferredSize(new java.awt.Dimension(25, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        jPanel1.add(jButton1, gridBagConstraints);

        btnRelatorio.setText("Visualizar");
        btnRelatorio.setOpaque(false);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 0);
        jPanel1.add(btnRelatorio, gridBagConstraints);

        chRelatorio.setText("Todos Contato");
        chRelatorio.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel1.add(chRelatorio, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (this.txtCodigo.getText().equals("")) {
            this.contato = new Contato();
            this.contato.setNome(txtNome.getText());
            this.contato.setEmpresa(txtEmpresa.getText());
            preencherDadosTelefone();
            this.contatoController.salva(this.contato);
            this.telefoneController.salvar(this.telefone);
            this.txtCodigo.setText(this.contato.getId().toString());
        } else {
            preencherDadosTelefone();
            this.telefoneController.salvar(this.telefone);
        }
        txtTelefone.setText("");
        atualizaTabelaTelefone();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void preencherDadosTelefone() {
        this.telefone = new Telefone();
        this.telefone.setContato(this.contato);
        this.telefone.setOperador(cboOperadora.getSelectedItem().toString());
        this.telefone.setNumero(Integer.parseInt(txtTelefone.getText()));
        this.contato.getTelefones().add(telefone);
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void novo() {
        this.txtCodigo.setText("");
        this.txtNome.setText("");
        this.txtEmpresa.setText("");
        this.txtTelefone.setText("");
        this.tbTelefone.setModel(new DefaultTableModel());
        this.contato = new Contato();
        this.telefone = new Telefone();
        this.telefones = new ArrayList();
        this.contatoController = new ContatoController();
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //this.contatoController.excluir(this.contato);
        if (tbTelefone.getSelectedRow() == -1) {
            this.contatoController.excluir(this.contato);
            novo();
        } else {
            Long idTelefone = Long.parseLong(tbTelefone.getValueAt(tbTelefone.getSelectedRow(), 0).toString());
            this.telefoneController.excluiPeloId(idTelefone);
            atualizaContato();
            atualizaTabelaTelefone();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListaContato listaContato = new ListaContato(this, true);
        listaContato.preencherTabela();
        listaContato.setVisible(true);
        this.contato = listaContato.contato;
        if (this.contato != null) {
            atualizaTabelaTelefone();
            preencheTelaContato();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        List<Contato> contatos = new ArrayList<>();
        contatos.add(this.contato);
        this.contatoController.relatorio(contatos, chRelatorio.isSelected());
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JComboBox cboOperadora;
    private javax.swing.JCheckBox chRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbTelefone;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void atualizaTabelaTelefone() {
        if (this.contato != null) {
            this.tmTelefone = new TableModelTelefone(this.contato.getTelefones());
        }
        tbTelefone.setModel(this.tmTelefone);
        tbTelefone.setAutoscrolls(true);

    }

    private void atualizaContato() {
        Long idContato = Long.parseLong(txtCodigo.getText());
        this.contato = this.contatoController.contatoPorId(idContato);
    }

    private void preencheTelaContato() {
        this.txtCodigo.setText(this.contato.getId().toString());
        this.txtNome.setText(this.contato.getNome());
        this.txtEmpresa.setText(this.contato.getEmpresa());
    }
}
