package br.com.agendamysql.view;

import br.com.agendamysql.controller.ContatoController;
import br.com.agendamysql.modelo.Contato;
import br.com.agendamysql.tableModel.TableModelContato;
import java.util.List;

public class ListaContato extends javax.swing.JDialog {

    public Contato contato;
    private ContatoController contatoController;
    private List<Contato> contatos;
    private TableModelContato tmContato;

    public ListaContato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.contatoController = new ContatoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContato = new javax.swing.JTable();
        btnSeleciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Lista de Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 9, 6, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtNome.setMaximumSize(new java.awt.Dimension(240, 20));
        txtNome.setMinimumSize(new java.awt.Dimension(240, 20));
        txtNome.setPreferredSize(new java.awt.Dimension(240, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 9, 2, 3);
        jPanel1.add(txtNome, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(240, 240));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(240, 240));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(240, 240));

        tbContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbContato.setOpaque(false);
        jScrollPane1.setViewportView(tbContato);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 9, 2, 3);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        btnSeleciona.setText("Seleciona");
        btnSeleciona.setOpaque(false);
        btnSeleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel1.add(btnSeleciona, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaActionPerformed
        this.contato = new Contato();
        Long codigo = (Long) tbContato.getValueAt(tbContato.getSelectedRow(), 0);
        for (int i = 0; i < this.contatos.size(); i++) {
            if (this.contatos.get(i).getId() == codigo) {
                this.contato = this.contatos.get(i);
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnSelecionaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleciona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbContato;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    public void preencherTabela() {
        this.contatos = contatoController.listaContatos();
        this.tmContato = new TableModelContato(this.contatos);
        this.tbContato.setModel(this.tmContato);
    }
}
